name: "Deploy Static Files to Server"

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: FTP
    steps:
      - name: "Checking Out"
        uses: actions/checkout@v4.1.4

      - name: Setting Up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "21"
          cache: "yarn"

      - name: Installing dependencies
        run: yarn

      - name: Generating Static Files
        run: yarn build

      - name: "Caching build"
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: cresteem.com
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_UNAME }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          local-dir: ./opensource/
          server-dir: /opensource/
