name: "Deploy Static Files to Server"

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: FTP
    steps:
      - name: "Checking Out"
        uses: actions/checkout@v4.1.4

      - name: Setting Up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "21"
          cache: "yarn"

      - name: Installing dependencies
        run: yarn

      - name: Generating Static Files
        run: yarn build

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_UNAME }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./opensource/
          server-dir: /opensource/
